# Generated by Django 3.0.6 on 2020-05-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200224_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='FakeNews',
        ),
    ]
